locator1:
  command: start locator 
  ports:
   - '1527:1527'
   - '10334:10334'
  image: 'snappydatainc/snappydata:latest'
  restart: always
  target_num_containers: 1
  working_dir: /opt/snappydata/
server1:
  command: 'bash -c "sleep 10 && start server -locators=locator1:10334 -client-port=1528 -J-Dgemfirexd.hostname-for-clients=$DOCKERCLOUD_CONTAINER_FQDN"'
  image: 'snappydatainc/snappydata:latest'
  restart: always
  target_num_containers: 1
  links:
    - locator1
  ports:
    - '1528:1528'
  sequential_deployment: true
  working_dir: /opt/snappydata/
snappy-lead1:
  command: 'bash -c "sleep 20 && start lead -locators=locator1:10334"'
  image: 'snappydatainc/snappydata:latest'
  restart: always
  target_num_containers: 1
  links:
    - server1
  ports:
    - '4040:4040'
  sequential_deployment: true
  working_dir: /opt/snappydata/